started backend
osscameroon/camerapps.com pull request #28
Opened 2021-11-20 20:40 UTC by jefcolbi

2021-11-26 18:38 UTC, abdounasser202 requested changes

2021-11-26 18:38 UTC, abdounasser202 commented on backend/camerapps/settings.py
> +SECRET_KEY = 'django-insecure-&i1!9_xfz&icb6-!yd52)6e6)ru8&*8%_g#*nhr^i0!k_183r='
SECRET_KEY should be in a .env file

2022-01-25 18:33 UTC, elhmn commented
I am closing this as it does not really fit with the plan we have for this project at the moment. @jefcolbi thanks a lot for this contribution but it was unfortunately not very aligned with the roadmap 🙇‍♂️

2022-01-25 18:33 UTC, closed without merging

2022-01-25 19:36 UTC, abdounasser202 commented
Can we please have the roadmap of this project ?

2022-01-25 19:49 UTC, elhmn commented
> Can we please have the roadmap of this project ?

As it has been discussed several times in the chat that this project is not supposed to receive any major improvement as another version is currently being built on this repository https://github.com/osscameroon/camerapps. I am currently unaware of the status  of that new version but I will have a chat with the project maintainers to figure it out soon.

2022-01-26 00:07 UTC, jefcolbi commented
:)